"use client";

import { useState } from "react";
import { ArrowLeft, FileDown, Printer } from "lucide-react";
import { useRouter } from "next/navigation";
import { Spinner } from "@/components/ui/feedback";

/**
 * Tinggi minimum satu potongan halaman (px CSS). Dipakai agar garis potong
 * tidak pernah menyusut jadi nyaris nol saat "didorong" menjauhi kartu.
 */
const MIN_SLICE_CSS = 32;

/**
 * Tangkap elemen .report-container & simpan sebagai PDF via jsPDF + html2canvas.
 *
 * Pemotongan per halaman sengaja dibuat sadar-batas: elemen yang ditandai
 * `data-pdf-avoid-break` (kartu TC, tabel ringkasan, metadata, bug, catatan)
 * tidak boleh terbelah dua halaman. Tanpa ini, irisan canvas tetap memotong
 * kartu di tengah karena html2canvas menghasilkan SATU gambar panjang.
 */
async function downloadContainerAsPdf(fileName: string): Promise<void> {
  const [{ jsPDF }, { default: html2canvas }] = await Promise.all([
    import("jspdf"),
    import("html2canvas"),
  ]);
  const el = document.querySelector<HTMLElement>(".report-container");
  if (!el) throw new Error("Konten report tidak ditemukan.");

  // Render canvas full-width resolusi tinggi; action bar (Kembali/Download/Print)
  // dibuang dari klon dokumen agar tidak ikut masuk hasil PDF.
  const canvas = await html2canvas(el, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
    windowWidth: el.scrollWidth,
    onclone: (doc) => {
      doc.querySelector(".report-action-bar")?.remove();
      // Footer HTML digantikan footer per-halaman jsPDF (timestamp + nomor).
      doc.querySelector(".report-footer")?.remove();
    },
  });

  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D context tidak tersedia.");

  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const margin = 8;
  const contentW = pageW - margin * 2;
  const y = margin;

  const cssWidth = el.offsetWidth || el.scrollWidth || 1;
  // px canvas per px CSS (html2canvas memakai scale 2).
  const scale = canvas.width / cssWidth;
  // Tinggi satu halaman penuh, dalam px canvas.
  const pagePx = ((pageH - margin * 2) * canvas.width) / contentW;
  const minSlicePx = MIN_SLICE_CSS * scale;

  // Batas potong "aman" dari elemen yang tidak boleh terbelah.
  const rootRect = el.getBoundingClientRect();
  const ranges = Array.from(
    el.querySelectorAll<HTMLElement>("[data-pdf-avoid-break]")
  )
    .map((node) => {
      const r = node.getBoundingClientRect();
      return [(r.top - rootRect.top) * scale, (r.bottom - rootRect.top) * scale] as [
        number,
        number,
      ];
    })
    .filter(([top, bottom]) => bottom - top > 1)
    .sort((a, b) => a[0] - b[0]);

  /**
   * Geser garis potong ke atas bila jatuh di tengah elemen yang tidak boleh
   * terbelah. Bila ruang tersisa di halaman lebih kecil dari `minSlicePx`,
   * biarkan terbelah — elemen itu sendiri lebih tinggi dari satu halaman,
   * sehingga memaksanya utuh akan membuat loop tak berujung.
   */
  const safeCut = (cut: number, start: number): number => {
    let c = cut;
    for (const [top, bottom] of ranges) {
      if (top >= c) break;
      if (bottom > c && top - start >= minSlicePx) c = top;
    }
    return c;
  };

  let pos = 0;
  let first = true;
  let guard = 0;
  while (pos < canvas.height && guard++ < 500) {
    const ideal = Math.min(pos + pagePx, canvas.height);
    const cut = ideal >= canvas.height ? canvas.height : safeCut(ideal, pos);
    const slicePx = Math.max(1, Math.round(cut - pos));
    const sliceHmm = (slicePx * contentW) / canvas.width;

    const slice = ctx.getImageData(0, pos, canvas.width, slicePx);
    const tmp = document.createElement("canvas");
    tmp.width = canvas.width;
    tmp.height = slicePx;
    tmp.getContext("2d")!.putImageData(slice, 0, 0);
    if (!first) pdf.addPage();
    pdf.addImage(tmp.toDataURL("image/png"), "PNG", margin, y, contentW, sliceHmm);
    first = false;
    pos += slicePx;
  }

  // Footer seragam di SETIAP halaman: timestamp generator (kiri) +
  // "Page X of Y" (kanan). Ditaruh di area margin bawah sehingga tidak
  // menimpa isi halaman.
  const totalPages = pdf.getNumberOfPages();
  const stamp = `Generated by Soulparking Test Case Management · ${new Date().toLocaleString("id-ID")}`;
  pdf.setFontSize(8);
  pdf.setTextColor(148, 163, 184);
  for (let page = 1; page <= totalPages; page++) {
    pdf.setPage(page);
    pdf.text(stamp, margin, pageH - 4);
    pdf.text(`Page ${page} of ${totalPages}`, pageW - margin, pageH - 4, { align: "right" });
  }

  pdf.save(`${fileName || "test-run-report"}.pdf`);
}

export function ReportActionBar({
  detailUrl,
  fileName,
}: {
  detailUrl: string;
  fileName?: string;
}) {
  const router = useRouter();
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    if (downloading) return;
    setDownloading(true);
    try {
      await downloadContainerAsPdf(fileName ?? "test-run-report");
    } catch (err) {
      console.error("Gagal membuat PDF:", err);
      alert("Gagal membuat PDF. Coba gunakan Print > Save as PDF.");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div
      className="report-action-bar"
      style={{
        position: "fixed",
        bottom: "1.5rem",
        right: "1.5rem",
        zIndex: 999,
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
      }}
    >
      <button
        type="button"
        onClick={() => router.push(detailUrl)}
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "0.35rem",
          padding: "0.45rem 0.9rem",
          borderRadius: 999,
          border: "1px solid #D1D5DB",
          background: "#fff",
          color: "#374151",
          fontSize: "0.82rem",
          fontWeight: 600,
          cursor: "pointer",
        }}
      >
        <ArrowLeft size={14} /> Kembali
      </button>
      <button
        type="button"
        onClick={handleDownload}
        disabled={downloading}
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "0.35rem",
          padding: "0.45rem 0.9rem",
          borderRadius: 999,
          border: "1px solid #D1D5DB",
          background: "#fff",
          color: "#374151",
          fontSize: "0.82rem",
          fontWeight: 600,
          cursor: downloading ? "wait" : "pointer",
        }}
      >
        {downloading ? (
          <>
            <Spinner size={13} /> Menyiapkan PDF…
          </>
        ) : (
          <>
            <FileDown size={14} /> Download PDF
          </>
        )}
      </button>
      <button
        type="button"
        onClick={() => window.print()}
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "0.35rem",
          padding: "0.45rem 0.9rem",
          borderRadius: 999,
          border: "none",
          background: "#2563EB",
          color: "#fff",
          fontSize: "0.82rem",
          fontWeight: 600,
          cursor: "pointer",
        }}
      >
        <Printer size={14} /> Print
      </button>
    </div>
  );
}
